# Generated by Django 5.0.6 on 2024-06-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetails',
            name='description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='videodetails',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
