# Generated by Django 5.0.6 on 2024-06-15 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_videodetails_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoDetails',
            new_name='VideoDetail',
        ),
    ]
