# Generated by Django 5.0.6 on 2024-06-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_rename_videodetails_videodetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoDetail',
            new_name='Video',
        ),
    ]
